//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ActorX.rc
//
#define IDS_LIBDESCRIPTION              1
#define IDS_CATEGORY                    2
#define IDS_CLASS_NAME                  3
#define IDS_PARAMS                      4
#define IDD_PANEL                       101
#define IDD_AUXPANEL                    102
#define IDD_AUXPANEL2                   103
#define IDD_ABOUTBOX                    110
#define IDD_ACTORMANAGER                111
#define IDB_BITMAP2                     112
#define IDD_SCENEINFO                   113
#define IDC_CURSOR1                     114
#define IDC_CURSOR2                     116
#define IDC_CURSOR3                     117
#define IDD_BONETREE                    122
#define IDC_CURSOR4                     123
#define IDB_BITMAP1                     125
#define IDC_CURSOR5                     126
#define IDC_CURSOR6                     128
#define IDB_BITMAP3                     129
#define IDC_CURSOR7                     130
#define IDD_STATICMESH                  131
#define IDD_VERTMESH                    132
#define IDB_BITMAP4                     133
#define IDC_CLOSEBUTTON                 1000
#define IDC_DOSTUFF                     1000
#define IDC_PATH                        1006
#define IDC_BROWSE                      1007
#define IDC_TEST                        1008
#define IDC_FNAME                       1009
#define IDC_SKINFILENAME                1009
#define IDC_LOGOUNREAL                  1010
#define IDC_ANIMNAME                    1011
#define IDC_ANIMFILENAME                1012
#define IDC_LISTIN                      1015
#define IDC_LISTOUT                     1016
#define IDC_BUT_AM                      1020
#define IDC_EVAL                        1021
#define IDC_ANIMSAVE                    1023
#define IDC_SAVEAS                      1024
#define IDC_ANIMSAVEAS                  1024
#define IDC_ANIMLOAD                    1026
#define IDC_BUTTON5                     1028
#define IDC_MOVEOUT                     1028
#define IDC_BUTTON6                     1029
#define IDC_MOVEIN                      1029
#define IDC_BUTTON8                     1031
#define IDC_COPYOUT                     1031
#define IDC_BUTTON9                     1032
#define IDC_COPYIN                      1032
#define IDC_ANI_INFO                    1036
#define IDC_SKINSIZE                    1037
#define IDC_ANIMFRAMES                  1037
#define IDC_TESTCOMPRESS                1040
#define IDC_APPLYCOMPRESS               1041
#define IDC_SAVESKIN                    1044
#define IDC_SAVEANIM                    1045
#define IDC_DIGESTANIM                  1045
#define IDC_EDITTARGETSIZE              1049
#define IDC_SIZEORIGINAL                1053
#define IDC_BONESCURRENT                1053
#define IDC_SIZECOMPRESSED2             1054
#define IDC_MESHES                      1054
#define IDC_SIZECURRENT                 1055
#define IDC_PHYMESHES                   1055
#define IDC_TOTALBONES                  1056
#define IDC_BIPBONES                    1057
#define IDC_BIPEDBONES                  1058
#define IDC_LINKEDBONES                 1059
#define IDC_DUMMIES                     1060
#define IDC_TRIANGLES3                  1061
#define IDC_MAXBONES                    1062
#define IDC_FACES                       1063
#define IDC_TRIANGLES4                  1064
#define IDC_VERTS                       1065
#define IDC_FRAMES                      1066
#define IDC_TICKSFRAME                  1067
#define IDC_TOTALTIME                   1068
#define IDC_TOTALLINKS                  1069
#define IDC_LOCKROOTX                   1072
#define IDC_FIXROOT                     1075
#define IDC_EDIT_ATIME                  1077
#define IDC_SPIN_ATIME                  1078
#define IDC_CHECKSKIN1                  1079
#define IDC_CHECKSKINALLT               1079
#define IDC_CHECKSKIN2                  1080
#define IDC_CHECKSKINALLS               1080
#define IDC_EDITANIMRANGE               1082
#define IDC_CHECKSKINALLP               1085
#define IDC_CHECKCULLDUMMIES            1086
#define IDC_CHECKSKINNOS                1087
#define IDC_POSEZERO                    1088
#define IDC_CHECKMATERIALS              1089
#define IDC_CHECKQUADTEX                1089
#define IDC_ANIMSECONDS                 1090
#define IDC_TOTALSIZE                   1091
#define IDC_ANIMRANGE                   1092
#define IDC_ANIMMANAGER                 1093
#define IDC_CHECKCULLROOT               1095
#define IDC_CHECKAUTOQUAD               1096
#define IDC_CHECKTEXPCX                 1096
#define IDC_DELIN                       1097
#define IDC_EDITRATE                    1098
#define IDC_EDITGROUP                   1099
#define IDC_EDITNAME                    1100
#define IDC_DELOUT                      1101
#define IDC_EDITKEYREDUCTION            1105
#define IDC_CHECKSCALE                  1108
#define IDC_UPDATEANIM                  1109
#define IDC_CHECKSCRIPTOUT              1110
#define IDC_CHECKNOLOG                  1111
#define IDC_CHECKASCIIOUT               1112
#define IDC_EDITSTARTBONE               1113
#define IDC_LISTTEST                    1116
#define IDC_VERTEXOUT                   1118
#define IDC_EDITCLASS                   1119
#define IDC_EDITBASE                    1120
#define IDC_SAVESCRIPT                  1122
#define IDC_EXPLICIT                    1123
#define IDC_INSHUF                      1129
#define IDC_OUTSHUF                     1130
#define IDC_PACKAGENAME                 1131
#define IDC_BONESELECT                  1135
#define IDC_TREE1                       1136
#define IDC_BATCHMAX                    1137
#define IDC_BATCHPATH                   1138
#define IDC_BATCHSRC                    1139
#define IDC_LOADANIMAS                  1140
#define IDC_EDITTEX1                    1141
#define IDC_EDITTEX2                    1145
#define IDC_EDITTEX7                    1148
#define IDC_CHECKSMOOTH                 1149
#define IDC_EDITTEX3                    1150
#define IDC_EDITTEX4                    1151
#define IDC_EDITTEX5                    1152
#define IDC_EDITTEX6                    1153
#define IDC_EDITTEX0                    1154
#define IDC_CHECKSINGLE                 1155
#define IDC_EXPORTBRUSH                 1157
#define IDC_BRUSHFILENAME               1158
#define IDC_BRUSHBROWSE                 1159
#define IDC_BRUSHPATH                   1160
#define IDC_READMAT                     1161
#define IDC_ANIMSORT                    1162
#define IDC_CHECKPERSIST                1170
#define IDC_CHECKPERSISTSETTINGS        1171
#define IDC_CHECKPERSISTPATHS           1172
#define IDC_QUICKSAVE                   1173
#define IDC_CHECK_STRIP_REFERENCE_PREFIX 1173
#define IDC_BATCH                       1175
#define IDC_QUICKSAVEDISK               1176
#define IDC_CHECKFORCERATE              1177
#define IDC_PERSISTRATE                 1178
#define IDC_UNDERSCORETOSPACE           1179
#define IDC_CHECKDOUNSMOOTH             1181
#define IDC_EXPORTVERTEX                1182
#define IDC_EDITVERTEXRANGE             1183
#define IDC_CHECKDOTANGENTS             1184
#define IDC_EDITFIXEDSCALE              1185
#define IDC_CHECKFIXEDSCALE             1186
#define IDC_CHECKAPPENDVERTEX           1187
#define IDC_CHECKUNDERSCORE             1190
#define IDC_CHECKUNTEXTURED             1191
#define IDC_CHECKSELECTEDSTATIC         1191
#define IDC_EDITOUTPATH                 1192
#define IDC_CHECKGEOMNAME               1193
#define IDC_CHECKTRIANGLE               1195
#define ID_EXPORTMESH                   1196
#define IDC_CHECKSUPPRESS               1198
#define IDC_BROWSEOUT                   1199
#define IDC_CHECKAUTOTRI                1200
#define IDC_CHECKNOPOPUP                1203
#define IDC_CHECKT3D                    1205
#define IDC_CHECKHIERBONES              1206
#define IDC_DOBAKEANIMS                 1207
#define IDC_CHECKCONSOLIDATE            1208
#define IDC_DOSECONDUVSETSKINNED        1209
#define IDC_INCLUDEBLENDSHAPES          1209
#define IDC_COLOR                       1456
#define IDC_EDIT                        1490
#define IDC_EDIT_A                      1490
#define IDC_EDIT_ACOMP                  1491
#define IDC_SPIN                        1496
#define IDC_SPIN_A                      1496
#define IDC_SPIN_ACOMP                  1497

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1210
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif

#define IDC_STATIC						(-1)
